kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops
spec:
    replicas: 2
    selector:    #Tells the container which pods to watch/belong to
    matchLabels:
      app: devops
    template:
      metadata:
        labels:
          app: devops
    spec:
      containers:
      - name: devops
        image: aishwaryas23/pipeline-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
