apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-deployment
  labels:
    app: kub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub
  template:
    metadata:
      labels:
        app: kub 
    spec:
      containers:
      - name: kubserver
        image: aishwaryas23/pipeline:latest
        ports:
        - containerPort: 3000
