kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops
spec:
    replicas: 2
    selector:    #Tells the container which pods to watch/belong to
    matchLabels:
      app: devops
    template:
      metadata:
        labels:
          app: devops
    spec:
      containers:
      - name: devops
        image: aishwaryas23/pipeline-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

kind: Service        #Defines to create service type object
apiVersion: v1
metadata:
  name: devops
  labels:
    app: devops
spec:
  selector:
    app: devops    #Apply this service to any pods which has the specific label
  type: LoadBalancer      #Specifies the service type i.e. ClusterIP or NodePort
  ports:
  - port: 8080 
    targetPort: 80          #Container port exposed
    nodePort: 31200         #Pods port
