kind: Service        #Defines to create service type object
apiVersion: v1
metadata:
  name: devops
  labels:
    app: devops
spec:
  ports:
    - port: 8080 
      targetPort: 80          #Container port exposed
      nodePort: 31200         #Pods port
  selector:
    app: devops    #Apply this service to any pods which has the specific label
  type: LoadBalancer      #Specifies the service type i.e. ClusterIP or NodePort
  
